### PR TITLE
Complete vala parser

### PR DESCRIPTION
**Pull request by albfan**
- Added test suite
- Added keywords
- Avoid set statements (if, while, for) as methods
- Added namespace parsing
- Complete copyright
- Fix code details (typos, parser order)

### CODE REVIEW

**Comment by albfan** [comment]
If changes make sense, would be great to rebase on top of upstream master.

**Comment by rrthomas** [comment]
Hey, any progress on this? I'm a recent convert to Vala looking for a bit more tools support…!

**Comment by masatake** [comment]
No progress. You can finish the work.

**Comment by rrthomas** [comment]
Thanks, what's left to do?

**Comment by masatake** [comment]
> Thanks, what's left to do?

I'm sorry but I don't know. 
See the old discussions about Vala. https://github.com/universal-ctags/ctags/issues/621 and https://github.com/universal-ctags/ctags/pull/2320.

**Comment by rrthomas** [comment]
I read the discussions, and nothing seemed to be left to do. I rebased https://github.com/albfan/ctags/tree/vala on master, and got it to build (there was just one call in ctags that had been renamed since the branch was last updated: `tokenDestroy` became `tokenDelete`).

The test pass.

I ran it on a Vala project, and it looks good.

I saw that you wanted the commits for Vala squashed, so I squashed it down to two commits: one for your initial work, and one for Alberto's, with my very minor fix at the end.

**Comment by masatake** [comment]
Could you open a pull request at https://github.com/universal-ctags/ctags/pulls ? I will review it.

**Comment by rrthomas** [comment]
Thanks, I've opened a pull request. I found a bug (rather, something missing) and added a test. I kept my work in separate commits so it's easier to review, but of course I can squash them down for merging.

**Comment by albfan** [comment]
Great so I found https://github.com/universal-ctags/ctags/pull/2677 and seems to work. I probably can contribute there as plumbings are ready

**Pull request closed without merging**
